using BetterLyrics.Core.Helpers;

namespace BetterLyrics.Core.Models.Lyrics;

public class LyricsData
{
    public LyricsData()
    {
    }

    public LyricsData(List<LyricsLine> lyricsLines)
    {
        LyricsLines = lyricsLines;
    }

    public List<LyricsLine> LyricsLines { get; set; } = [];

    public string? LanguageCode
    {
        get => field ?? LanguageHelper.DetectLanguageCode(LyricsLines.Select(line => line.PrimaryText));
        set => field = value;
    }

    public bool AutoGenerated { get; set; } = false;

    public string WrappedOriginalText =>
        string.Join(StringHelper.NewLine, LyricsLines.Select(line => line.PrimaryText));

    public bool IsWordByWord => LyricsLines.Any(x => x.IsPrimaryHasRealSyllableInfo);
}