// 2025/6/23 by Zhe Fang

using BetterLyrics.Core.Enums;
using BetterLyrics.Core.Extensions;
using BetterLyrics.Core.Interfaces.Providers;
using BetterLyrics.Core.Interfaces.Services;
using BetterLyrics.Core.Models.Entities;
using BetterLyrics.Core.Models.Lyrics;
using BetterLyrics.Core.Models.Settings;
using CommunityToolkit.Mvvm.DependencyInjection;
using Lyricify.Lyrics.Helpers.Optimization;
using Lyricify.Lyrics.Parsers;
using Microsoft.Extensions.Logging;

namespace BetterLyrics.Core.Helpers.Lyrics.ContentParser;

public partial class LyricsContentParser
{
    private static readonly ILogger<LyricsContentParser> _logger =
        Ioc.Default.GetRequiredService<ILogger<LyricsContentParser>>();

    private static readonly IGlobalToastProvider _globalToastProvider =
        Ioc.Default.GetRequiredService<IGlobalToastProvider>();

    private List<LyricsData> _lyricsDataArr = [];

    public List<LyricsData> Parse(LyricsCacheItem? lyricsSearchResult)
    {
        _logger.LogInformation("LyricsContentParser.Parse");
        _lyricsDataArr = [];
        if (string.IsNullOrWhiteSpace(lyricsSearchResult?.Raw))
        {
            _lyricsDataArr.Add(LyricsData.GetNotfoundPlaceholder());
        }
        else
        {
            switch (lyricsSearchResult.Raw.DetectFormat())
            {
                case LyricsFormat.Lrc:
                case LyricsFormat.Eslrc:
                    ParseLrc(lyricsSearchResult.Raw);
                    break;
                case LyricsFormat.Qrc:
                    ParseQrcKrc(QrcParser.Parse(lyricsSearchResult.Raw).Lines);
                    break;
                case LyricsFormat.Krc:
                    ParseQrcKrc(KrcParser.Parse(lyricsSearchResult.Raw).Lines);
                    break;
                case LyricsFormat.Ttml:
                    ParseTtml(lyricsSearchResult.Raw);
                    break;
            }

            if (_lyricsDataArr.Count == 0) _lyricsDataArr.Add(LyricsData.GetNotfoundPlaceholder());
        }

        LoadTranslation(lyricsSearchResult);
        LoadTransliteration(lyricsSearchResult);
        GenerateTransliterationLyricsData();

        EnsureSyllables(lyricsSearchResult?.Duration);
        EnsureEndMs(lyricsSearchResult?.Duration);

        return _lyricsDataArr;
    }

    public async Task<(LyricsData, TransliterationSearchProvider?, TranslationSearchProvider?)> ParseAsync(
        ITranslationService translationService,
        ITransliterationService transliterationService,
        TranslationSettings settings,
        LyricsCacheItem? lyricsSearchResult,
        CancellationToken token
    )
    {
        TransliterationSearchProvider? transliterationSearchProvider = null;
        TranslationSearchProvider? translationSearchProvider = null;

        Parse(lyricsSearchResult);

        var main = _lyricsDataArr.First();

        // 歌词过滤
        if (settings.IsFilterEnabled)
            main?.LyricsLines.RemoveAll(x =>
                InfoLines.IsInfoLine(x.PrimaryText));

        // 应用音译
        LyricsData? phoneticLyricsData = null;
        // 已解析歌词内寻找
        if (settings.IsChineseRomanizationEnabled && main.LanguageCode == LanguageHelper.ChineseCode)
        {
            phoneticLyricsData = settings.ChineseRomanization switch
            {
                ChineseRomanization.Pinyin => _lyricsDataArr.FirstOrDefault(x =>
                    x.LanguageCode == LanguageHelper.PinyinCode),
                ChineseRomanization.Jyutping => _lyricsDataArr.FirstOrDefault(x =>
                    x.LanguageCode == LanguageHelper.JyutpingCode),
                _ => null
            };
            if (phoneticLyricsData != null)
            {
                main.SetPhoneticText(phoneticLyricsData);
                if (phoneticLyricsData.AutoGenerated)
                    transliterationSearchProvider = TransliterationSearchProvider.BetterLyrics;
                else
                    transliterationSearchProvider = lyricsSearchResult?.Provider.ToTransliterationSearchProvider();
            }
        }
        else if (settings.IsJapaneseRomanizationEnabled && main.LanguageCode == LanguageHelper.JapaneseCode)
        {
            phoneticLyricsData = _lyricsDataArr.FirstOrDefault(x => x.LanguageCode == LanguageHelper.RomanCode);
            if (phoneticLyricsData != null)
            {
                main.SetPhoneticText(phoneticLyricsData);
                transliterationSearchProvider = lyricsSearchResult?.Provider.ToTransliterationSearchProvider();
            }
            else
            {
                var romaji = string.Empty;
                try
                {
                    (romaji, transliterationSearchProvider) =
                        await transliterationService.TransliterateTextAsync(main.WrappedOriginalText,
                            LanguageHelper.RomanCode, token);
                    token.ThrowIfCancellationRequested();

                    _lyricsDataArr.FirstOrDefault()?.SetTransliteration(romaji);
                }
                catch (OperationCanceledException)
                {
                    throw;
                }
                catch (Exception ex)
                {
                    _globalToastProvider.Show("Error", ex.Message, MessageSeverity.Error);
                }
            }
        }

        // 应用翻译
        if (settings.IsTranslationEnabled && main.LanguageCode != settings.SelectedTargetLanguageCode)
        {
            var found = _lyricsDataArr.Where(x => x.LanguageCode == settings.SelectedTargetLanguageCode)
                .OrderByDescending(x => x.LyricsLines.Count).FirstOrDefault();
            if (found != null)
            {
                main.SetTranslatedText(found);
                translationSearchProvider = lyricsSearchResult?.Provider.ToTranslationSearchProvider();
            }
            else if (settings.IsLibreTranslateEnabled)
            {
                var translated = string.Empty;
                try
                {
                    translated = await translationService.TranslateTextAsync(main.WrappedOriginalText,
                        settings.SelectedTargetLanguageCode, token);
                    token.ThrowIfCancellationRequested();

                    _lyricsDataArr.FirstOrDefault()?.SetTranslation(translated);
                    translationSearchProvider = TranslationSearchProvider.LibreTranslate;
                }
                catch (OperationCanceledException)
                {
                    throw;
                }
                catch (Exception ex)
                {
                    _globalToastProvider.Show("LibreTranslateFailed", ex.Message, MessageSeverity.Error);
                }
            }
        }

        // 应用简体中文/繁体中文
        if (main.LanguageCode == LanguageHelper.ChineseCode)
            foreach (var item in main.LyricsLines)
                switch (settings.ChineseConversion)
                {
                    case ChineseConversion.Unspecified:
                        break;
                    case ChineseConversion.S2T:
                        item.PrimaryText = LanguageHelper.ConvertSCToTC(item.PrimaryText);
                        break;
                    case ChineseConversion.T2S:
                        item.PrimaryText = LanguageHelper.ConvertTCToSC(item.PrimaryText);
                        break;
                }

        if (settings.SelectedTargetLanguageCode == LanguageHelper.ChineseCode)
            foreach (var item in main.LyricsLines)
                switch (settings.ChineseConversion)
                {
                    case ChineseConversion.Unspecified:
                        break;
                    case ChineseConversion.S2T:
                        item.SecondaryText = LanguageHelper.ConvertSCToTC(item.SecondaryText);
                        break;
                    case ChineseConversion.T2S:
                        item.SecondaryText = LanguageHelper.ConvertTCToSC(item.SecondaryText);
                        break;
                }

        token.ThrowIfCancellationRequested();

        return (main, transliterationSearchProvider, translationSearchProvider);
    }

    private void LoadTranslation(LyricsCacheItem? lyricsSearchResult)
    {
        if (!string.IsNullOrWhiteSpace(lyricsSearchResult?.Translation))
            switch (lyricsSearchResult.Provider)
            {
                case LyricsSearchProvider.QQ:
                case LyricsSearchProvider.Kugou:
                case LyricsSearchProvider.Netease:
                    ParseLrc(lyricsSearchResult.Translation);
                    break;
            }
    }

    private void LoadTransliteration(LyricsCacheItem? lyricsSearchResult)
    {
        if (!string.IsNullOrWhiteSpace(lyricsSearchResult?.Transliteration))
            switch (lyricsSearchResult.Provider)
            {
                case LyricsSearchProvider.Netease:
                    ParseLrc(lyricsSearchResult.Transliteration);
                    //_lyricsDataArr.LastOrDefault()?.LanguageCode = LanguageHelper.RomanCode;
                    break;
            }
    }

    /// <summary>
    ///     在音译不存在的情况下生成音译歌词
    /// </summary>
    private void GenerateTransliterationLyricsData()
    {
        var main = _lyricsDataArr.FirstOrDefault();
        if (main != null)
        {
            var languageCode = main.LanguageCode;
            if (languageCode == LanguageHelper.ChineseCode)
            {
                if (!_lyricsDataArr.Any(x => x.LanguageCode == LanguageHelper.PinyinCode))
                    _lyricsDataArr.Add(new LyricsData
                    {
                        LanguageCode = LanguageHelper.PinyinCode,
                        AutoGenerated = true,
                        LyricsLines = main.LyricsLines.Select(line => new LyricsLine
                        {
                            StartMs = line.StartMs,
                            EndMs = line.EndMs,
                            PrimaryText = LanguageHelper.ConvertHanziToPinyin(line.PrimaryText),
                            PrimarySyllables = line.PrimarySyllables.Select(c => new BaseLyrics
                            {
                                StartMs = c.StartMs,
                                EndMs = c.EndMs,
                                Text = LanguageHelper.ConvertHanziToPinyin(c.Text),
                                StartIndex = c.StartIndex
                            }).ToList()
                        }).ToList()
                    });

                if (!_lyricsDataArr.Any(x => x.LanguageCode == LanguageHelper.JyutpingCode))
                    _lyricsDataArr.Add(new LyricsData
                    {
                        LanguageCode = LanguageHelper.JyutpingCode,
                        AutoGenerated = true,
                        LyricsLines = main.LyricsLines.Select(line => new LyricsLine
                        {
                            StartMs = line.StartMs,
                            EndMs = line.EndMs,
                            PrimaryText = LanguageHelper.ConvertHanziToJyutping(line.PrimaryText),
                            PrimarySyllables = line.PrimarySyllables.Select(c => new BaseLyrics
                            {
                                StartMs = c.StartMs,
                                EndMs = c.EndMs,
                                Text = LanguageHelper.ConvertHanziToJyutping(c.Text),
                                StartIndex = c.StartIndex
                            }).ToList()
                        }).ToList()
                    });
            }
        }
    }

    /// <summary>
    ///     基于已经处理好的音节，确保整句话的 EndMs
    ///     Invoke this after <see cref="EnsureSyllables" />
    /// </summary>
    private void EnsureEndMs(double? duration)
    {
        foreach (var lyricsData in _lyricsDataArr)
        {
            if (lyricsData?.LyricsLines == null) continue;
            var lines = lyricsData.LyricsLines;

            for (var i = 0; i < lines.Count; i++)
            {
                var line = lines[i];
                if (line == null) continue;

                var isLastLine = i + 1 >= lines.Count;
                // 如果是最后一句，使用歌曲总长作为参考
                var nextLineStartMs = isLastLine ? (int)(duration ?? 0) * 1000 : lines[i + 1].StartMs;

                // 确保基础的 EndMs（基于最后的音节）
                if (line.EndMs == null)
                {
                    if (line.PrimarySyllables.Count > 0)
                        line.EndMs = line.PrimarySyllables.Last().EndMs;
                    else
                        line.EndMs = line.StartMs >= nextLineStartMs ? line.StartMs + 1000 : nextLineStartMs;
                }
            }
        }
    }

    /// <summary>
    ///     优先确保音节的完整性（补全缺失的 EndMs，或者为纯文本歌词生成平均音节）
    /// </summary>
    private void EnsureSyllables(double? duration)
    {
        foreach (var lyricsData in _lyricsDataArr)
        {
            if (lyricsData?.LyricsLines == null) continue;
            var lines = lyricsData.LyricsLines;

            for (var i = 0; i < lines.Count; i++)
            {
                var line = lines[i];
                if (line == null) continue;

                // 预先获取下一句的 StartMs（如果是最后一句，用歌曲总长或者 0 代替）
                var nextLineStartMs = i + 1 < lines.Count ? lines[i + 1].StartMs : (int)(duration ?? 0) * 1000;

                // 1. 如果已经有音节，按照新逻辑修复音节的 EndMs
                if (line.PrimarySyllables.Count > 0)
                {
                    for (var j = 0; j < line.PrimarySyllables.Count; j++)
                    {
                        var syllable = line.PrimarySyllables[j];
                        if (syllable.EndMs == null)
                        {
                            if (j < line.PrimarySyllables.Count - 1)
                            {
                                // 不是最后一个音节：取后一个音节的 StartMs
                                syllable.EndMs = line.PrimarySyllables[j + 1].StartMs;
                            }
                            else
                            {
                                // 最后一个音节
                                if (syllable.StartMs >= nextLineStartMs)
                                    // 背景歌词特殊情况：起唱时间已超过下一句，直接默认持续1秒
                                    syllable.EndMs = syllable.StartMs + 1000;
                                else
                                    // 默认持续1秒，和下一句的 StartMs 比较，取较小的
                                    syllable.EndMs = Math.Min(syllable.StartMs + 1000, nextLineStartMs);
                            }
                        }
                    }
                }
                // 2. 如果没有音节（如 LRC 格式），则基于预估的整句时间自动生成平均分布的音节
                else if (!line.IsPrimaryHasRealSyllableInfo)
                {
                    var content = line.PrimaryText;
                    var length = content.Length;
                    if (length == 0) continue;

                    // 预估整句话的 EndMs（此时 EnsureEndMs 还没跑，需要临时计算用于平分时间）
                    var tempLineEndMs = line.EndMs ??
                                        (line.StartMs >= nextLineStartMs ? line.StartMs + 1000 : nextLineStartMs);
                    var durationMs = tempLineEndMs - line.StartMs;

                    if (durationMs <= 0) continue;

                    var avgSyllableDuration = durationMs / length;
                    if (avgSyllableDuration == 0) continue;

                    for (var j = 0; j < length; j++)
                        line.PrimarySyllables.Add(new BaseLyrics
                        {
                            Text = content[j].ToString(),
                            StartIndex = j,
                            StartMs = line.StartMs + avgSyllableDuration * j,
                            EndMs = line.StartMs + avgSyllableDuration * (j + 1)
                        });
                }
            }
        }
    }
}