// Auto-Generated by BetterLyrics.DevTools

using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace BetterLyrics.WinUI3.PluginConfigs;

internal static class BetterLyrics_Plugins_Source_LRCLIB_Config
{
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Diagnostics.DebuggableAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Diagnostics.DebuggableAttribute.DebuggingModes))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Diagnostics.DebuggerHiddenAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Double))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Exception))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.IDisposable))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Net.Http.HttpClient))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Net.Http.HttpContent))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Net.Http.HttpResponseMessage))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Nullable<>))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Reflection.AssemblyCompanyAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Reflection.AssemblyConfigurationAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Reflection.AssemblyCopyrightAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Reflection.AssemblyDescriptionAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Reflection.AssemblyFileVersionAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Reflection.AssemblyInformationalVersionAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Reflection.AssemblyMetadataAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Reflection.AssemblyProductAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Reflection.AssemblyTitleAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Runtime.CompilerServices.AsyncStateMachineAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Runtime.CompilerServices.AsyncTaskMethodBuilder<>))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Runtime.CompilerServices.CompilationRelaxationsAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Runtime.CompilerServices.CompilerGeneratedAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Runtime.CompilerServices.DefaultInterpolatedStringHandler))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Runtime.CompilerServices.IAsyncStateMachine))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Runtime.CompilerServices.NullableAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Runtime.CompilerServices.NullableContextAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Runtime.CompilerServices.RefSafetyRulesAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Runtime.CompilerServices.RuntimeCompatibilityAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Runtime.CompilerServices.TaskAwaiter<>))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Runtime.Versioning.SupportedOSPlatformAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Runtime.Versioning.TargetFrameworkAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Runtime.Versioning.TargetPlatformAttribute))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Text.Json.JsonElement))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Text.Json.JsonSerializer))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Text.Json.JsonValueKind))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Text.Json.Serialization.Metadata.JsonTypeInfo<>))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Threading.CancellationToken))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Threading.Tasks.Task))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Threading.Tasks.Task<>))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Type))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.Uri))]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(System.ValueType))]
    [ModuleInitializer]
    internal static void Initialize()
    {
        // This method runs automatically on startup to keep types from being trimmed.
    }
}
