using BetterLyrics.WinUI3.Helper;
using System.Collections.Generic;
using System.Linq;

namespace BetterLyrics.WinUI3.Models.Lyrics
{
    public class LyricsData
    {
        public List<LyricsLine> LyricsLines { get; set; } = [];
        public string? LanguageCode
        {
            get => field ?? LanguageHelper.DetectLanguageCode(WrappedOriginalText);
            set => field = value;
        }
        public bool AutoGenerated { get; set; } = false;
        public string WrappedOriginalText => string.Join(StringHelper.NewLine, LyricsLines.Select(line => line.PrimaryText));

        public LyricsData()
        {
        }

        public LyricsData(List<LyricsLine> lyricsLines)
        {
            LyricsLines = lyricsLines;
        }

    }
}
