using Mono.Cecil;
using System.Text;
using System.Text.RegularExpressions;
using System.Diagnostics;

class Program
{
    static HashSet<string> _mergedAssemblies = new HashSet<string>();
    static HashSet<string> _mergedSystemTypes = new HashSet<string>();
    static string _currentScanDirectory = "";

    static void Main(string[] args)
    {
        if (args.Length > 0)
        {
            try
            {
                string scanPath = args[0].Replace("\"", "").Trim();
                string targetNs = args.Length > 1 ? args[1] : "BetterLyrics.WinUI3";
                string prefix = args.Length > 2 ? args[2] : "Plugin";
                string outputDir = args.Length > 3 ? args[3].Replace("\"", "").Trim() : scanPath;

                Console.WriteLine($"[Analyzer] Scanning: {scanPath}");
                Console.WriteLine($"[Analyzer] Output to: {outputDir}");

                RunBatch(scanPath, targetNs, prefix, outputDir, silent: true);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[Analyzer] Error: {ex.Message}");
                Environment.Exit(1);
            }
            return;
        }

        Console.WriteLine("==================================================");
        Console.WriteLine("   Plugin Dependency Analyzer (Auto-CLI Ready)    ");
        Console.WriteLine("==================================================");

        while (true)
        {
            _mergedAssemblies.Clear();
            _mergedSystemTypes.Clear();

            Console.WriteLine("\n1. Enter Plugin FOLDER path (or 'exit'):");
            Console.Write("> ");
            string input = Console.ReadLine();
            if (string.IsNullOrWhiteSpace(input)) continue;
            if (input.Trim().ToLower() == "exit") break;

            string path = input.Replace("\"", "").Trim();
            if (!Directory.Exists(path)) { Console.WriteLine("[ERROR] Folder not found."); continue; }

            Console.WriteLine("2. Enter Namespace (Default: BetterLyrics.WinUI3):");
            Console.Write("> ");
            string ns = Console.ReadLine().Trim();
            if (string.IsNullOrWhiteSpace(ns)) ns = "BetterLyrics.WinUI3";

            string prefix = new DirectoryInfo(path).Name;
            Console.WriteLine($"3. Enter prefix (Default: {prefix}):");
            Console.Write("> ");
            string p = Console.ReadLine().Trim();
            if (!string.IsNullOrWhiteSpace(p)) prefix = p;

            string interactiveOutputDir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "AnalyzerOutput");

            RunBatch(path, ns, prefix, interactiveOutputDir, silent: false);
        }
    }

    static void RunBatch(string scanPath, string ns, string prefix, string outputDir, bool silent)
    {
        _currentScanDirectory = scanPath;
        _mergedAssemblies.Clear();
        _mergedSystemTypes.Clear();

        ProcessDirectory(scanPath);

        GenerateFiles(prefix, ns, outputDir, silent);
    }

    static void GenerateFiles(string prefix, string rootNamespace, string outputDir, bool silent)
    {
        Directory.CreateDirectory(outputDir);

        string xmlFileName = $"{prefix}_TrimmerRoots.xml";
        string csFileName = $"{prefix}_TrimmingConfig.cs";

        string assemblyName = rootNamespace;
        string codeNamespace = $"{rootNamespace}.PluginConfigs";

        string configClassName = $"{prefix.Replace(".", "_").Replace(" ", "_")}_Config";
        string fullConfigClassName = $"{codeNamespace}.{configClassName}";

        string xmlPath = Path.Combine(outputDir, xmlFileName);
        string csPath = Path.Combine(outputDir, csFileName);

        var xmlBuilder = new StringBuilder();
        xmlBuilder.AppendLine("");
        xmlBuilder.AppendLine("<linker>");

        if (_mergedAssemblies.Count > 0)
        {
            foreach (var asm in _mergedAssemblies.OrderBy(n => n))
                xmlBuilder.AppendLine($"  <assembly fullname=\"{asm}\" preserve=\"all\" />");
        }

        xmlBuilder.AppendLine($"  <assembly fullname=\"{assemblyName}\">");
        xmlBuilder.AppendLine($"    <type fullname=\"{fullConfigClassName}\" preserve=\"all\" />");
        xmlBuilder.AppendLine($"  </assembly>");

        xmlBuilder.AppendLine("</linker>");

        var csBuilder = new StringBuilder();
        csBuilder.AppendLine("// Auto-Generated by PluginAnalyzer");
        csBuilder.AppendLine("using System.Diagnostics.CodeAnalysis;");
        csBuilder.AppendLine("using System.Runtime.CompilerServices;");
        csBuilder.AppendLine("");

        csBuilder.AppendLine($"namespace {codeNamespace};");

        csBuilder.AppendLine($"internal static class {configClassName}");
        csBuilder.AppendLine("{");

        foreach (var type in _mergedSystemTypes.OrderBy(n => n))
        {
            csBuilder.AppendLine($"    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof({type}))]");
        }

        csBuilder.AppendLine("    [ModuleInitializer]");
        csBuilder.AppendLine("    internal static void Initialize()");
        csBuilder.AppendLine("    {");
        csBuilder.AppendLine("        // This method runs automatically on startup.");
        csBuilder.AppendLine("    }");
        csBuilder.AppendLine("}");

        File.WriteAllText(xmlPath, xmlBuilder.ToString());
        File.WriteAllText(csPath, csBuilder.ToString());

        if (!silent)
        {
            Console.WriteLine($"[Analyzer] Generated: {xmlFileName}");
            Process.Start("explorer.exe", outputDir);
        }
        else
        {
            Console.WriteLine($"[Analyzer] Created: {xmlPath}");
            Console.WriteLine($"[Analyzer] Created: {csPath}");
        }
    }

    static void ProcessDirectory(string folderPath)
    {
        var files = Directory.GetFiles(folderPath, "*.dll");
        foreach (var file in files)
        {
            if (!IsHostOrSystemBinary(Path.GetFileName(file))) AnalyzeDll(file);
        }
    }

    static void AnalyzeDll(string path)
    {
        try
        {
            var resolver = new DefaultAssemblyResolver();
            resolver.AddSearchDirectory(Path.GetDirectoryName(path));
            using var assembly = AssemblyDefinition.ReadAssembly(path, new ReaderParameters { AssemblyResolver = resolver });

            foreach (var typeRef in assembly.MainModule.GetTypeReferences())
            {
                if (typeRef.Scope is AssemblyNameReference asmRef && !IsIgnoredDependency(asmRef.Name) && !IsLocalDll(asmRef.Name))
                    _mergedAssemblies.Add(asmRef.Name);

                if (typeRef.FullName.StartsWith("System.") || typeRef.FullName.StartsWith("Microsoft.Win32"))
                    _mergedSystemTypes.Add(FormatTypeName(typeRef));
            }
        }
        catch { }
    }

    static bool IsLocalDll(string asmName) => File.Exists(Path.Combine(_currentScanDirectory, asmName + ".dll"));

    static bool IsHostOrSystemBinary(string fileName)
    {
        fileName = fileName.ToLower();
        return fileName.StartsWith("betterlyrics.") && !fileName.Contains("plugin") ||
               fileName.StartsWith("microsoft.windows") || fileName.StartsWith("winrt.") || fileName.StartsWith("system.");
    }

    static bool IsIgnoredDependency(string asmName) => asmName.Contains("BetterLyrics") || asmName.Contains("WindowsAppSDK") || asmName.Contains("Microsoft.Windows") || asmName == "netstandard" || asmName == "mscorlib";

    static string FormatTypeName(TypeReference type)
    {
        if (type.FullName == "System.Void") return "void";

        string name = type.FullName;

        name = name.Replace("/", ".");

        if (name.Contains("`"))
        {
            name = Regex.Replace(name, @"`(\d+)", match =>
            {
                int argsCount = int.Parse(match.Groups[1].Value);
                return "<" + new string(',', Math.Max(0, argsCount - 1)) + ">";
            });
        }

        return name;
    }
}