<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<UseWinUI>true</UseWinUI>
		<EnableDynamicLoading>true</EnableDynamicLoading>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="customizeDict.txt">
			<PackagePath>contentFiles\any\any\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<Pack>true</Pack>
		</Content>
		<Content Include="unidic\AUTHORS">
			<PackagePath>contentFiles\any\any\unidic\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<Pack>true</Pack>
		</Content>
		<Content Include="unidic\BSD">
			<PackagePath>contentFiles\any\any\unidic\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<Pack>true</Pack>
		</Content>
		<Content Include="unidic\ChangeLog">
			<PackagePath>contentFiles\any\any\unidic\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<Pack>true</Pack>
		</Content>
		<Content Include="unidic\char.bin">
			<PackagePath>contentFiles\any\any\unidic\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<Pack>true</Pack>
		</Content>
		<Content Include="unidic\COPYING">
			<PackagePath>contentFiles\any\any\unidic\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<Pack>true</Pack>
		</Content>
		<Content Include="unidic\dicrc">
			<PackagePath>contentFiles\any\any\unidic\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<Pack>true</Pack>
		</Content>
		<Content Include="unidic\GPL">
			<PackagePath>contentFiles\any\any\unidic\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<Pack>true</Pack>
		</Content>
		<Content Include="unidic\INSTALL">
			<PackagePath>contentFiles\any\any\unidic\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<Pack>true</Pack>
		</Content>
		<Content Include="unidic\LGPL">
			<PackagePath>contentFiles\any\any\unidic\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<Pack>true</Pack>
		</Content>
		<Content Include="unidic\matrix.bin">
			<PackagePath>contentFiles\any\any\unidic\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<Pack>true</Pack>
		</Content>
		<Content Include="unidic\sys.dic">
			<PackagePath>contentFiles\any\any\unidic\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<Pack>true</Pack>
		</Content>
		<Content Include="unidic\unidic-mecab.pdf">
			<PackagePath>contentFiles\any\any\unidic\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<Pack>true</Pack>
		</Content>
		<Content Include="unidic\unk.dic">
			<PackagePath>contentFiles\any\any\unidic\</PackagePath>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<PackageCopyToOutput>true</PackageCopyToOutput>
			<Pack>true</Pack>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BetterLyrics.Core\BetterLyrics.Core.csproj" >
			<Private>false</Private>
			<ExcludeAssets>runtime</ExcludeAssets>
		</ProjectReference>
		<ProjectReference Include="..\RomajiConverter.Core\RomajiConverter.Core.csproj" />
	</ItemGroup>

</Project>
