<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
		<RootNamespace>BetterLyrics.WinUI3</RootNamespace>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<UseWinUI>true</UseWinUI>
		<Nullable>enable</Nullable>
		<LangVersion>preview</LangVersion>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="TemplateSelector\**" />
		<Compile Remove="ViewModels\Lyrics\**" />
		<Content Remove="TemplateSelector\**" />
		<Content Remove="ViewModels\Lyrics\**" />
		<EmbeddedResource Remove="TemplateSelector\**" />
		<EmbeddedResource Remove="ViewModels\Lyrics\**" />
		<None Remove="TemplateSelector\**" />
		<None Remove="ViewModels\Lyrics\**" />
		<Page Remove="TemplateSelector\**" />
		<Page Remove="ViewModels\Lyrics\**" />
		<PRIResource Remove="TemplateSelector\**" />
		<PRIResource Remove="ViewModels\Lyrics\**" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="Assets\Segoe Fluent Icons.ttf" />
		<None Remove="Assets\Wiki82.profile.xml" />
		<None Remove="Controls\AboutControl.xaml" />
		<None Remove="Controls\AlbumArtAreaEffectSettingsControl.xaml" />
		<None Remove="Controls\AppSettingsControl.xaml" />
		<None Remove="Controls\DemoWindowGrid.xaml" />
		<None Remove="Controls\ExtendedSlider.xaml" />
		<None Remove="Controls\FontFamilyAutoSuggestBox.xaml" />
		<None Remove="Controls\ImageSwitcher.xaml" />
		<None Remove="Controls\LyricsSearchControl.xaml" />
		<None Remove="Controls\LyricsStyleSettingsControl.xaml" />
		<None Remove="Controls\LyricsWindowSettingsControl.xaml" />
		<None Remove="Controls\LyricsWindowSwitchControl.xaml" />
		<None Remove="Controls\MediaSettingsControl.xaml" />
		<None Remove="Controls\NowPlayingBar.xaml" />
		<None Remove="Controls\PlaybackSettingsControl.xaml" />
		<None Remove="Controls\PropertyRow.xaml" />
		<None Remove="Controls\RemoteServerConfigControl.xaml" />
		<None Remove="Controls\ShortcutTextBox.xaml" />
		<None Remove="Controls\SystemTray.xaml" />
		<None Remove="Controls\WindowSettingsControl.xaml" />
		<None Remove="Views\LyricsSearchWindow.xaml" />
		<None Remove="Views\LyricsWindowSwitchWindow.xaml" />
		<None Remove="Views\MusicGalleryPage.xaml" />
		<None Remove="Views\MusicGalleryWindow.xaml" />
		<None Remove="Views\SettingsWindow.xaml" />
		<None Remove="Views\SystemTrayWindow.xaml" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="Logo.ico" />
	</ItemGroup>
	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="3v.EvtSource" Version="2.0.0" />
		<PackageReference Include="CommunityToolkit.Labs.WinUI.Controls.OpacityMaskView" Version="0.1.251021-build.2365" />
		<PackageReference Include="CommunityToolkit.Labs.WinUI.Shimmer" Version="0.1.250703-build.2173" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="CommunityToolkit.WinUI.Behaviors" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Controls.Segmented" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Converters" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Extensions" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Helpers" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Media" Version="8.2.251219" />
		<PackageReference Include="CommunityToolkit.WinUI.Triggers" Version="8.2.251219" />
		<PackageReference Include="ComputeSharp.D2D1.WinUI" Version="3.2.0" />
		<PackageReference Include="csharp-pinyin" Version="1.0.1" />
		<PackageReference Include="DevWinUI.Controls" Version="9.8.1" />
		<PackageReference Include="Dubya.WindowsMediaController" Version="2.5.6" />
		<PackageReference Include="F23.StringSimilarity" Version="7.0.1" />
		<PackageReference Include="FlaUI.UIA3" Version="5.0.0" />
		<PackageReference Include="FluentFTP" Version="53.0.2" />
		<PackageReference Include="H.NotifyIcon.WinUI" Version="2.4.1" />
		<PackageReference Include="Hqub.Last.fm" Version="2.5.1" />
		<PackageReference Include="Interop.UIAutomationClient" Version="10.19041.0" />
		<PackageReference Include="Lyricify.Lyrics.Helper-NativeAot" Version="0.1.4-alpha.5" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
		<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.3.2" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.7175" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.251106002" />
		<PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
		<PackageReference Include="NTextCat" Version="0.3.65" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
		<PackageReference Include="SMBLibrary" Version="1.5.5.1" />
		<PackageReference Include="System.Drawing.Common" Version="10.0.1" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.1" />
		<PackageReference Include="TagLibSharp" Version="2.3.0" />
		<PackageReference Include="Ude.NetStandard" Version="1.2.0" />
		<PackageReference Include="Vanara.PInvoke.DwmApi" Version="4.2.1" />
		<PackageReference Include="Vanara.PInvoke.Gdi32" Version="4.2.1" />
		<PackageReference Include="Vanara.PInvoke.Shell32" Version="4.2.1" />
		<PackageReference Include="Vanara.PInvoke.User32" Version="4.2.1" />
		<PackageReference Include="Vanara.Windows.Shell" Version="4.2.1" />
		<PackageReference Include="VCollab.DiscordRichPresence" Version="1.7.0" />
		<PackageReference Include="WebDav.Client" Version="2.9.0" />
		<PackageReference Include="WinUI3Localizer" Version="2.3.0" />
		<PackageReference Include="WinUIEx" Version="2.9.0" />
		<PackageReference Include="z440.atl.core" Version="7.9.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\ColorThief.WinUI3\ColorThief.WinUI3.csproj" />
	  <ProjectReference Include="..\..\Impressionist\Impressionist\Impressionist.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Page Update="Rendering\InAppLyricsRenderer.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Rendering\DesktopLyricsRenderer.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<!--Disable Trimming for Specific Packages-->
	<ItemGroup>
		<TrimmerRootAssembly Include="FlaUI.UIA3" />
		<TrimmerRootAssembly Include="Interop.UIAutomationClient" />
		<TrimmerRootAssembly Include="NAudio.Wasapi" />
		<TrimmerRootAssembly Include="TagLibSharp" />
		<TrimmerRootAssembly Include="Vanara.PInvoke.DwmApi" />
		<TrimmerRootAssembly Include="Vanara.PInvoke.Gdi32" />
		<TrimmerRootAssembly Include="Vanara.PInvoke.Shell32" />
		<TrimmerRootAssembly Include="Vanara.PInvoke.User32" />
		<TrimmerRootAssembly Include="Vanara.Windows.Shell" />
	</ItemGroup>
	<ItemGroup>
	  <Content Update="Assets\AIMP.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\AlbumArtPlaceholder.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Alipay.jpg">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\AMLLPlayer.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\AppleMusic.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Chrome.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Edge.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\FluidEffect.bin">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Empty.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\EmptyBox.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\EmptyState.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\foobar2000.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\HyPlayer.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\iTunes.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\KugouMusic.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\LastFM.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Leaf.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Listen1.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Logo.ico">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Logo.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\LXMusic.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\MediaPlayerWindows11.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\MoeKoeMusic.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\MusicBee.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\NetEaseCloudMusic.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Page.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\PlanetMusic.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\PotPlayer.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\QQMusic.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Question.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\SaltPlayerForWindows.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Segoe Fluent Icons.ttf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Spotify.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\WeChatReward.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="Assets\Wiki82.profile.xml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\FontFamilyAutoSuggestBox.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\LyricsStyleSettingsControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\LyricsWindowSwitchWindow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\LyricsWindowSwitchControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\DemoWindowGrid.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\LyricsWindowSettingsControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\LyricsSearchWindow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\LyricsSearchControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\ShortcutTextBox.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\ExtendedSlider.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\LyricsEffectSettingsControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\MediaSettingsControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\PlaybackSettingsControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\AlbumArtAreaStyleSettingsControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\LyricsBackgroundSettingsControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\AppSettingsControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\MusicGalleryWindow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\MusicGalleryPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Views\SettingsWindow.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Controls\SystemTray.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
	  <PRIResource Update="Strings\de\Resources.resw">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </PRIResource>
	  <PRIResource Update="Strings\en\Resources.resw">
	    <Generator></Generator>
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </PRIResource>
	  <PRIResource Update="Strings\es\Resources.resw">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </PRIResource>
	  <PRIResource Update="Strings\fr\Resources.resw">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </PRIResource>
	  <PRIResource Update="Strings\ja\Resources.resw">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </PRIResource>
	  <PRIResource Update="Strings\ko\Resources.resw">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </PRIResource>
	  <PRIResource Update="Strings\ru\Resources.resw">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </PRIResource>
	  <PRIResource Update="Strings\zh-Hans\Resources.resw">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </PRIResource>
	  <PRIResource Update="Strings\zh-Hant\Resources.resw">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </PRIResource>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\RemoteServerConfigControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\NowPlayingBar.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Views\SystemTrayWindow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\WindowSettingsControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\AlbumArtAreaEffectSettingsControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\ImageSwitcher.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\ShadowImage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\PropertyRow.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\AboutControl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<!-- Publish Properties -->
	<PropertyGroup>
		<PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
		<PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
		<PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
		<PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
		<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
	</PropertyGroup>
	<PropertyGroup>
		<DefineConstants>$(DefineConstants)</DefineConstants>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>Logo.ico</ApplicationIcon>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ShouldCreateLogs>True</ShouldCreateLogs>
		<AdvancedSettingsExpanded>True</AdvancedSettingsExpanded>
		<UpdateAssemblyVersion>False</UpdateAssemblyVersion>
		<UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
		<UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
		<UpdatePackageVersion>True</UpdatePackageVersion>
		<AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
		<InheritWinAppVersionFrom>AssemblyVersion</InheritWinAppVersionFrom>
		<PackageVersionSettings>AssemblyVersion.None.None</PackageVersionSettings>
	</PropertyGroup>
</Project>
