using Mono.Cecil;
using System.Text;
using System.Text.RegularExpressions;

namespace BetterLyrics.DevTools.Generators
{
    public static class TrimmerGenerator
    {
        private static HashSet<string> _mergedAssemblies = new HashSet<string>();
        private static HashSet<string> _mergedSystemTypes = new HashSet<string>();
        private static string _currentScanDirectory = "";

        public static void Run(string targetDllPath, string outputDir)
        {
            Console.WriteLine("[Trim] Starting dependency analysis...");

            _mergedAssemblies.Clear();
            _mergedSystemTypes.Clear();
            _currentScanDirectory = Path.GetDirectoryName(targetDllPath)!;

            string prefix = Path.GetFileNameWithoutExtension(targetDllPath);
            string targetNs = "BetterLyrics.WinUI3";

            ProcessDirectory(_currentScanDirectory);

            GenerateFiles(prefix, targetNs, outputDir);
        }

        private static void ProcessDirectory(string folderPath)
        {
            var files = Directory.GetFiles(folderPath, "*.dll");
            foreach (var file in files)
            {
                if (!IsHostOrSystemBinary(Path.GetFileName(file)))
                {
                    AnalyzeDll(file);
                }
            }
        }

        private static void AnalyzeDll(string path)
        {
            try
            {
                var resolver = new DefaultAssemblyResolver();
                resolver.AddSearchDirectory(Path.GetDirectoryName(path));

                using var assembly = AssemblyDefinition.ReadAssembly(path, new ReaderParameters { AssemblyResolver = resolver });

                foreach (var typeRef in assembly.MainModule.GetTypeReferences())
                {
                    if (typeRef.Scope is AssemblyNameReference asmRef && !IsIgnoredDependency(asmRef.Name) && !IsLocalDll(asmRef.Name))
                        _mergedAssemblies.Add(asmRef.Name);

                    if (typeRef.FullName.StartsWith("System.") || typeRef.FullName.StartsWith("Microsoft.Win32"))
                        _mergedSystemTypes.Add(FormatTypeName(typeRef));
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"   [Trim] Failed to analyze {Path.GetFileName(path)}: {ex.Message}");
            }
        }

        private static void GenerateFiles(string prefix, string rootNamespace, string outputDir)
        {
            string xmlFileName = $"{prefix}_TrimmerRoots.xml";
            string csFileName = $"{prefix}_TrimmingConfig.cs";

            string assemblyName = rootNamespace;
            string codeNamespace = $"{rootNamespace}.PluginConfigs";
            string configClassName = $"{prefix.Replace(".", "_").Replace(" ", "_")}_Config";
            string fullConfigClassName = $"{codeNamespace}.{configClassName}";

            string xmlPath = Path.Combine(outputDir, xmlFileName);
            string csPath = Path.Combine(outputDir, csFileName);

            var xmlBuilder = new StringBuilder();
            xmlBuilder.AppendLine("");
            xmlBuilder.AppendLine("<linker>");

            if (_mergedAssemblies.Count > 0)
            {
                foreach (var asm in _mergedAssemblies.OrderBy(n => n))
                    xmlBuilder.AppendLine($"  <assembly fullname=\"{asm}\" preserve=\"all\" />");
            }

            xmlBuilder.AppendLine($"  <assembly fullname=\"{assemblyName}\">");
            xmlBuilder.AppendLine($"    <type fullname=\"{fullConfigClassName}\" preserve=\"all\" />");
            xmlBuilder.AppendLine($"  </assembly>");
            xmlBuilder.AppendLine("</linker>");

            var csBuilder = new StringBuilder();
            csBuilder.AppendLine("// Auto-Generated by PluginAnalyzer");
            csBuilder.AppendLine("using System.Diagnostics.CodeAnalysis;");
            csBuilder.AppendLine("using System.Runtime.CompilerServices;");
            csBuilder.AppendLine("");
            csBuilder.AppendLine($"namespace {codeNamespace};");
            csBuilder.AppendLine($"internal static class {configClassName}");
            csBuilder.AppendLine("{");

            foreach (var type in _mergedSystemTypes.OrderBy(n => n))
            {
                csBuilder.AppendLine($"    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof({type}))]");
            }

            csBuilder.AppendLine("    [ModuleInitializer]");
            csBuilder.AppendLine("    internal static void Initialize()");
            csBuilder.AppendLine("    {");
            csBuilder.AppendLine("        // This method runs automatically on startup to keep types from being trimmed.");
            csBuilder.AppendLine("    }");
            csBuilder.AppendLine("}");

            File.WriteAllText(xmlPath, xmlBuilder.ToString());
            File.WriteAllText(csPath, csBuilder.ToString());

            Console.WriteLine($"   [Trim] Generated: {xmlFileName}");
            Console.WriteLine($"   [Trim] Generated: {csFileName}");
        }

        static bool IsLocalDll(string asmName) => File.Exists(Path.Combine(_currentScanDirectory, asmName + ".dll"));

        static bool IsHostOrSystemBinary(string fileName)
        {
            fileName = fileName.ToLower();
            return fileName.StartsWith("betterlyrics.") && !fileName.Contains("plugin") ||
                   fileName.StartsWith("microsoft.windows") || fileName.StartsWith("winrt.") || fileName.StartsWith("system.");
        }

        static bool IsIgnoredDependency(string asmName)
        {
            return asmName.Contains("BetterLyrics") ||
                   asmName.Contains("WindowsAppSDK") ||
                   asmName.Contains("Microsoft.Windows") ||
                   asmName == "netstandard" ||
                   asmName == "mscorlib";
        }

        static string FormatTypeName(TypeReference type)
        {
            if (type.FullName == "System.Void") return "void";
            string name = type.FullName;
            name = name.Replace("/", ".");
            if (name.Contains("`"))
            {
                name = Regex.Replace(name, @"`(\d+)", match =>
                {
                    int argsCount = int.Parse(match.Groups[1].Value);
                    return "<" + new string(',', Math.Max(0, argsCount - 1)) + ">";
                });
            }
            return name;
        }
    }
}