// 2025/6/23 by Zhe Fang

using BetterLyrics.WinUI3.Enums;
using BetterLyrics.WinUI3.Extensions;
using BetterLyrics.WinUI3.Helper;
using BetterLyrics.WinUI3.Models;
using Lyricify.Lyrics.Parsers;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace BetterLyrics.WinUI3.Parsers.LyricsParser
{
    public partial class LyricsParser
    {
        public List<LyricsData> LyricsDataArr { get; private set; } = [];

        public void Parse(SongInfo? songInfo, LyricsSearchResult? lyricsSearchResult)
        {
            LyricsDataArr = [];
            if (lyricsSearchResult?.Raw == null)
            {
                LyricsDataArr.Add(LyricsData.GetNotfoundPlaceholder((int)(songInfo?.DurationMs ?? 0)));
            }
            else
            {
                switch (lyricsSearchResult.Raw.DetectFormat())
                {
                    case LyricsFormat.Lrc:
                    case LyricsFormat.Eslrc:
                        ParseLrc(lyricsSearchResult.Raw);
                        break;
                    case LyricsFormat.Qrc:
                        ParseQrcKrc(QrcParser.Parse(lyricsSearchResult.Raw).Lines);
                        break;
                    case LyricsFormat.Krc:
                        ParseQrcKrc(KrcParser.Parse(lyricsSearchResult.Raw).Lines);
                        break;
                    case LyricsFormat.Ttml:
                        ParseTtml(lyricsSearchResult.Raw);
                        break;
                    default:
                        break;
                }
            }
            LoadTranslation(lyricsSearchResult);
            LoadTransliteration(lyricsSearchResult);
            GenerateTransliterationLyricsData();
        }

        private void LoadTranslation(LyricsSearchResult? lyricsSearchResult)
        {
            if (lyricsSearchResult?.Translation != null)
            {
                switch (lyricsSearchResult.Provider)
                {
                    case LyricsSearchProvider.QQ:
                    case LyricsSearchProvider.Kugou:
                    case LyricsSearchProvider.Netease:
                        ParseLrc(lyricsSearchResult.Translation);
                        break;
                    default:
                        break;
                }
            }
        }

        private void LoadTransliteration(LyricsSearchResult? lyricsSearchResult)
        {
            if (lyricsSearchResult?.Transliteration != null)
            {
                switch (lyricsSearchResult.Provider)
                {
                    case LyricsSearchProvider.Netease:
                        ParseLrc(lyricsSearchResult.Transliteration);
                        LyricsDataArr.LastOrDefault()?.LanguageCode = PhoneticHelper.RomanCode;
                        break;
                    default:
                        break;
                }
            }
        }

        /// <summary>
        /// 在音译不存在的情况下生成音译歌词
        /// </summary>
        private void GenerateTransliterationLyricsData()
        {
            var main = LyricsDataArr.FirstOrDefault();
            if (main != null)
            {
                string? languageCode = main.LanguageCode;
                if (languageCode == LanguageHelper.ChineseCode)
                {
                    if (!LyricsDataArr.Any(x => x.LanguageCode == PhoneticHelper.PinyinCode))
                    {
                        LyricsDataArr.Add(new LyricsData
                        {
                            LanguageCode = PhoneticHelper.PinyinCode,
                            AutoGenerated = true,
                            LyricsLines = main.LyricsLines.Select(line => new LyricsLine
                            {
                                StartMs = line.StartMs,
                                EndMs = line.EndMs,
                                OriginalText = PhoneticHelper.ToPinyin(line.OriginalText),
                                LyricsChars = line.LyricsChars.Select(c => new LyricsChar
                                {
                                    StartMs = c.StartMs,
                                    EndMs = c.EndMs,
                                    Text = PhoneticHelper.ToPinyin(c.Text),
                                    StartIndex = c.StartIndex
                                }).ToList()
                            }).ToList()
                        });
                    }
                    if (!LyricsDataArr.Any(x => x.LanguageCode == PhoneticHelper.JyutpingCode))
                    {
                        LyricsDataArr.Add(new LyricsData
                        {
                            LanguageCode = PhoneticHelper.JyutpingCode,
                            AutoGenerated = true,
                            LyricsLines = main.LyricsLines.Select(line => new LyricsLine
                            {
                                StartMs = line.StartMs,
                                EndMs = line.EndMs,
                                OriginalText = PhoneticHelper.ToJyutping(line.OriginalText),
                                LyricsChars = line.LyricsChars.Select(c => new LyricsChar
                                {
                                    StartMs = c.StartMs,
                                    EndMs = c.EndMs,
                                    Text = PhoneticHelper.ToJyutping(c.Text),
                                    StartIndex = c.StartIndex
                                }).ToList()
                            }).ToList()
                        });
                    }
                }
                else if (languageCode == LanguageHelper.JapaneseCode)
                {
                    if (!LyricsDataArr.Any(x => x.LanguageCode == PhoneticHelper.RomanCode))
                    {
                        LyricsDataArr.Add(new LyricsData
                        {
                            LanguageCode = PhoneticHelper.RomanCode,
                            AutoGenerated = true,
                            LyricsLines = main.LyricsLines.Select(line => new LyricsLine
                            {
                                StartMs = line.StartMs,
                                EndMs = line.EndMs,
                                OriginalText = PhoneticHelper.ToRomaji(line.OriginalText),
                                LyricsChars = line.LyricsChars.Select(c => new LyricsChar
                                {
                                    StartMs = c.StartMs,
                                    EndMs = c.EndMs,
                                    Text = PhoneticHelper.ToRomaji(c.Text),
                                    StartIndex = c.StartIndex
                                }).ToList()
                            }).ToList()
                        });
                    }
                }
            }
        }
    }
}
