title: BetterLyrics Docs
description: BetterLyrics Docs
theme: just-the-docs

url: https://jayfunc.github.io/BetterLyrics

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
