<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net10.0-windows10.0.26100.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>jayfunc</Authors>
        <Authors>jayfunc</Authors>
        <Version>1.0.2</Version>
        <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/jayfunc/BetterLyrics/tree/dev/src/BetterLyrics.Sdk</PackageProjectUrl>
        <RepositoryUrl>https://github.com/jayfunc/BetterLyrics/tree/dev/src/BetterLyrics.Sdk</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
		<RuntimeIdentifiers Condition="$(TargetFrameworks.Contains('windows10.0'))">win-x86;win-x64;win-arm64</RuntimeIdentifiers>
	</PropertyGroup>

    <ItemGroup>
        <None Include="README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NLanguageTag" Version="4.1.2" />
    </ItemGroup>

</Project>
