using ComputeSharp;
using ComputeSharp.D2D1;

namespace BetterLyrics.WinUI3.Shaders;

/// <summary>
///     Ported from
///     <see href="https://github.com/Storyteller-Studios/Isolation/blob/main/ShaderTest.UWP/Shaders/effect.hlsl" />.
/// </summary>
/// <param name="resolution"></param>
/// <param name="time"></param>
/// <param name="color1"></param>
/// <param name="color2"></param>
/// <param name="color3"></param>
/// <param name="color4"></param>
/// <param name="randomValue1"></param>
/// <param name="randomValue2"></param>
/// <param name="randomValue3"></param>
/// <param name="useHsvBlending"></param>
/// <param name="enableLightWave"></param>
/// <param name="enableDithering"></param>
[D2DInputCount(0)]
[D2DRequiresScenePosition]
[D2DShaderProfile(D2D1ShaderProfile.PixelShader50)]
[D2DGeneratedPixelShaderDescriptor]
public readonly partial struct FluidBackgroundEffect(
    float2 resolution,
    float time,
    float3 color1,
    float3 color2,
    float3 color3,
    float3 color4,
    float randomValue1,
    float randomValue2,
    float randomValue3,
    bool useHsvBlending,
    bool enableLightWave,
    bool enableDithering = true) : ID2D1PixelShader
{
    private float2 Rotate(float2 p, float a)
    {
        var c = Hlsl.Cos(a);
        var s = Hlsl.Sin(a);
        return new float2(
            p.X * c - p.Y * s,
            p.X * s + p.Y * c
        );
    }

    private float2 F_Hash(float2 p)
    {
        p = new float2(
            Hlsl.Dot(p, new float2(2127.1f, 81.17f)),
            Hlsl.Dot(p, new float2(1269.5f, 283.37f))
        );
        return Hlsl.Frac(Hlsl.Sin(p) * 43758.5453f);
    }

    private float F_Noise(float2 p)
    {
        var i = Hlsl.Floor(p);
        var f = Hlsl.Frac(p);
        var u = f * f * (3.0f - 2.0f * f);

        var n = Hlsl.Lerp(
            Hlsl.Lerp(
                Hlsl.Dot(-1.0f + 2.0f * F_Hash(i + new float2(0.0f, 0.0f)), f - new float2(0.0f, 0.0f)),
                Hlsl.Dot(-1.0f + 2.0f * F_Hash(i + new float2(1.0f, 0.0f)), f - new float2(1.0f, 0.0f)),
                u.X),
            Hlsl.Lerp(
                Hlsl.Dot(-1.0f + 2.0f * F_Hash(i + new float2(0.0f, 1.0f)), f - new float2(0.0f, 1.0f)),
                Hlsl.Dot(-1.0f + 2.0f * F_Hash(i + new float2(1.0f, 1.0f)), f - new float2(1.0f, 1.0f)),
                u.X),
            u.Y);
        return 0.5f + 0.5f * n;
    }

    private float Range(float val, float mi, float ma)
    {
        return val * (ma - mi) + mi;
    }

    private float3 Hsv2Rgb(float3 c)
    {
        var K = new float4(1.0f, 2.0f / 3.0f, 1.0f / 3.0f, 3.0f);
        var p = Hlsl.Abs(Hlsl.Frac(c.XXX + K.XYZ) * 6.0f - K.WWW);
        return c.Z * Hlsl.Lerp(K.XXX, Hlsl.Saturate(p - K.XXX), c.Y);
    }

    private float3 Rgb2Hsv(float3 c)
    {
        var K = new float4(0.0f, -1.0f / 3.0f, 2.0f / 3.0f, -1.0f);
        var p = Hlsl.Lerp(new float4(c.BG, K.WZ), new float4(c.GB, K.XY), Hlsl.Step(c.B, c.G));
        var q = Hlsl.Lerp(new float4(p.XYW, c.R), new float4(c.R, p.YZX), Hlsl.Step(p.X, c.R));

        var d = q.X - Hlsl.Min(q.W, q.Y);
        var e = 1.0e-10f;
        return new float3(Hlsl.Abs(q.Z + (q.W - q.Y) / (6.0f * d + e)), d / (q.X + e), q.X);
    }

    private float3 LightWave(float3 input, bool isHSV, float2 uv)
    {
        var hsv = isHSV ? input : Rgb2Hsv(input);
        var p = -1.0f + 1.5f * uv.XY;
        var t = time / 5.0f;
        var x = p.X;
        var y = p.Y;

        var mov0 = x + y + Hlsl.Cos(Hlsl.Sin(t) * 2.0f) * 100.0f + Hlsl.Sin(x / 100.0f) * 1000.0f;
        var mov1 = y / 0.3f + t;
        var mov2 = x / 0.2f;

        var c1 = Hlsl.Sin(mov1 + t + randomValue1) / 2.0f + mov2 / 2.0f - mov1 - mov2 + t;
        var c2 = Hlsl.Cos(c1 + Hlsl.Sin(mov0 / 1000.0f + t - randomValue2) + Hlsl.Sin(y / 40.0f + t + randomValue3) +
                          Hlsl.Sin((x + y) / 100.0f) * 3.0f);
        var c3 = Hlsl.Abs(Hlsl.Sin(c2 + Hlsl.Cos(mov1 + mov2 + c2) + Hlsl.Cos(mov2) + Hlsl.Sin(x / 1000.0f)));

        var col = Hsv2Rgb(new float3(
            Range(Hlsl.Abs(c2), hsv.X * 0.95f, hsv.X),
            Range(c3, hsv.Y, hsv.Y * 0.85f),
            Range(c3, hsv.Z, hsv.Z * 0.85f)));
        return col;
    }

    // Dithering Utilities
    private float RemapTri(float v)
    {
        // Convert uniform distribution into triangle-shaped distribution.
        var orig = v * 2.0f - 1.0f;
        v = orig / Hlsl.Sqrt(Hlsl.Abs(orig));
        v = Hlsl.Max(-1.0f, v); // Nerf the NaN generated by 0*rsqrt(0)
        v = v - Hlsl.Sign(orig) + 0.5f;
        return v;
    }

    private float3 RemapTri(float3 c)
    {
        return new float3(RemapTri(c.R), RemapTri(c.G), RemapTri(c.B));
    }

    private float3 ScreenSpaceDither(float2 vScreenPos, float time)
    {
        var colorDepth = 32.0f;
        var dotValue = Hlsl.Dot(new float2(131.0f, 312.0f), vScreenPos.XY + time);
        var vDither = new float3(dotValue, dotValue, dotValue);
        vDither.XYZ = Hlsl.Frac(vDither.XYZ / new float3(103.0f, 71.0f, 97.0f));
        return RemapTri(vDither.XYZ) / colorDepth;
    }

    public float4 Execute()
    {
        var scene = D2D.GetScenePosition().XY;
        var uv = scene / resolution;

        var tuv = uv;
        tuv -= 0.5f;

        var degree = F_Noise(new float2(time * 0.1f, tuv.X * tuv.Y));

        tuv = Rotate(tuv, Hlsl.Radians((degree - 0.5f) * 720.0f + 180.0f));

        var frequency = 5.0f;
        var amplitude = 25.0f;
        var speed = time * 0.75f;

        var diter = enableDithering ? ScreenSpaceDither(scene, time) : new float3(0.0f, 0.0f, 0.0f);

        tuv.X += Hlsl.Sin(tuv.Y * frequency + speed) / amplitude;
        tuv.Y += Hlsl.Sin(tuv.X * frequency * 1.5f + speed) / (amplitude * 0.5f);

        float3 c1 = 0, c2 = 0, c3 = 0, c4 = 0;
        if (useHsvBlending)
        {
            c1 = Rgb2Hsv(color1);
            c2 = Rgb2Hsv(color2);
            c3 = Rgb2Hsv(color3);
            c4 = Rgb2Hsv(color4);
        }
        else
        {
            c1 = color1;
            c2 = color2;
            c3 = color3;
            c4 = color4;
        }

        var rotatedX = Rotate(tuv, Hlsl.Radians(-5.0f)).X;

        var layer1 = Hlsl.Lerp(c1, c2, Hlsl.SmoothStep(-0.3f, 0.2f, rotatedX));
        var layer2 = Hlsl.Lerp(c3, c4, Hlsl.SmoothStep(-0.3f, 0.2f, rotatedX));

        var finalComp = Hlsl.Lerp(layer1, layer2, Hlsl.SmoothStep(0.5f, -0.3f, tuv.Y));

        float4 result;

        if (enableLightWave)
            result = new float4(Hlsl.Saturate(LightWave(finalComp, useHsvBlending, uv) + diter), 1.0f);
        else if (useHsvBlending)
            result = new float4(Hlsl.Saturate(Hsv2Rgb(finalComp) + diter), 1.0f);
        else
            result = new float4(Hlsl.Saturate(finalComp + diter), 1.0f);

        return result;
    }
}